"""Theme pool for auto-generated list carousel packs.

Each theme maps to a TMDB Discover query. `generate_list_packs.py` picks
random unused themes weekly, fetches films, and writes complete packs to
data/ledgers/generated_list_packs.jsonl.

NICHE PRINCIPLE: every title should make a specific claim or apply an
unexpected angle — not just label a genre and era. "Five horror films from
the 80s" is a taxonomy. "Five 80s horror films where the suburbs are the
real monster" is a reason to care.

TMDB genre IDs reference:
  28=Action  12=Adventure  16=Animation  35=Comedy  80=Crime
  99=Documentary  18=Drama  14=Fantasy  36=History  27=Horror
  9648=Mystery  10749=Romance  878=Sci-Fi  53=Thriller  10752=War  37=Western
"""
from __future__ import annotations

THEMES: list[dict] = [

    # ------------------------------------------------------------------ #
    # Genre + era                                                          #
    # ------------------------------------------------------------------ #
    {
        "slug": "horror_80s",
        "title": "Five 80s horror films where the suburbs are the real monster",
        "subtitle": "it was never the creature.",
        "category": "HORROR LIST",
        "caption": "Five horror films from the 80s that understood what people were actually afraid of. Sources via TMDB.",
        "closing_headline": "The neighbourhood was always wrong.",
        "genre_ids": [27], "year_gte": 1980, "year_lte": 1989, "vote_avg_gte": 6.8,
    },
    {
        "slug": "horror_90s",
        "title": "The 90s reinvented horror and nobody noticed: five films that prove it",
        "subtitle": "before the decade got self-referential.",
        "category": "HORROR LIST",
        "caption": "Five horror films from the 90s that blurred genre lines before it was fashionable. Sources via TMDB.",
        "closing_headline": "The decade was weirder than you remember.",
        "genre_ids": [27], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 6.8,
    },
    {
        "slug": "crime_70s",
        "title": "Five 70s crime films made before the genre got polished into entertainment",
        "subtitle": "gritty, human, still unsurpassed.",
        "category": "CRIME LIST",
        "caption": "Five crime films from the 70s that feel like dispatches from another world. Sources via TMDB.",
        "closing_headline": "Nothing since has matched the texture.",
        "genre_ids": [80], "year_gte": 1970, "year_lte": 1979, "vote_avg_gte": 7.0,
    },
    {
        "slug": "sci_fi_80s",
        "title": "Five 80s sci-fi films that were describing the present, not the future",
        "subtitle": "they were right. they just had the date wrong.",
        "category": "SCI-FI LIST",
        "caption": "Five sci-fi films from the 80s that turned out to be journalism. Sources via TMDB.",
        "closing_headline": "Rewatch them. Then look outside.",
        "genre_ids": [878], "year_gte": 1980, "year_lte": 1989, "vote_avg_gte": 7.0,
    },
    {
        "slug": "sci_fi_90s",
        "title": "The 90s was the last decade sci-fi asked serious questions: five films",
        "subtitle": "before the genre became spectacle.",
        "category": "SCI-FI LIST",
        "caption": "Five sci-fi films from the 90s that used the genre to interrogate something real. Sources via TMDB.",
        "closing_headline": "Questions the genre stopped asking.",
        "genre_ids": [878], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 7.0,
    },
    {
        "slug": "thriller_90s",
        "title": "Five 90s thrillers where the twist is earned, not cheap",
        "subtitle": "before every ending became a reveal.",
        "category": "THRILLER LIST",
        "caption": "Five thrillers from the 90s where the conclusion reframes everything without cheating you. Sources via TMDB.",
        "closing_headline": "Go in blind.",
        "genre_ids": [53], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 7.0,
    },
    {
        "slug": "drama_2000s",
        "title": "Five 2000s dramas the decade was not ready for",
        "subtitle": "they flopped. critics were wrong. time corrected it.",
        "category": "DRAMA LIST",
        "caption": "Five dramas from the 2000s that deserved the conversation they did not get at the time. Sources via TMDB.",
        "closing_headline": "The reappraisal is overdue.",
        "genre_ids": [18], "year_gte": 2000, "year_lte": 2009, "vote_avg_gte": 7.2,
    },
    {
        "slug": "animation_all_time",
        "title": "Five animated films that are better than most live-action cinema",
        "subtitle": "animation is not a genre. it is a tool.",
        "category": "ANIMATION LIST",
        "caption": "Five animated films that operate at a level most live-action never reaches. Sources via TMDB.",
        "closing_headline": "The format is not the limitation.",
        "genre_ids": [16], "vote_avg_gte": 7.5, "vote_count_gte": 1000,
    },
    {
        "slug": "western_all_time",
        "title": "Five westerns that use the genre to talk about something that has nothing to do with guns",
        "subtitle": "the frontier is always a metaphor.",
        "category": "WESTERN LIST",
        "caption": "Five westerns where the setting exists to say something about everything else. Sources via TMDB.",
        "closing_headline": "The West is a state of mind.",
        "genre_ids": [37], "vote_avg_gte": 7.2,
    },
    {
        "slug": "documentary_essential",
        "title": "Five documentaries where not knowing what happens next is the whole point",
        "subtitle": "real life has no screenplay.",
        "category": "DOCUMENTARY LIST",
        "caption": "Five documentaries that use the unpredictability of reality as their primary tension. Sources via TMDB.",
        "closing_headline": "Nothing was scripted. That is why it works.",
        "genre_ids": [99], "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "comedy_dark",
        "title": "Five dark comedies that know something about the world that you have not admitted yet",
        "subtitle": "the laugh is the realisation.",
        "category": "COMEDY LIST",
        "caption": "Five dark comedies where the punchline is something true and uncomfortable. Sources via TMDB.",
        "closing_headline": "You will laugh. Then you will think about why.",
        "genre_ids": [35], "vote_avg_gte": 7.2, "vote_count_gte": 800,
    },
    {
        "slug": "mystery_essential",
        "title": "Five mystery films where the investigation matters more than the answer",
        "subtitle": "the process is the cinema.",
        "category": "MYSTERY LIST",
        "caption": "Five mystery films where what you learn along the way is more valuable than who did it. Sources via TMDB.",
        "closing_headline": "The answer is almost beside the point.",
        "genre_ids": [9648], "vote_avg_gte": 7.2,
    },
    {
        "slug": "history_films",
        "title": "Five historical films where the recreation reveals something the history books missed",
        "subtitle": "context changes everything.",
        "category": "HISTORY LIST",
        "caption": "Five historical films that use the past to show you something about how we got here. Sources via TMDB.",
        "closing_headline": "History is not over.",
        "genre_ids": [36], "vote_avg_gte": 7.0,
    },
    {
        "slug": "fantasy_underrated",
        "title": "Five fantasy films buried under blockbusters that are better than the blockbusters",
        "subtitle": "the box office was wrong.",
        "category": "FANTASY LIST",
        "caption": "Five fantasy films that were overlooked in favour of louder, more expensive things. Sources via TMDB.",
        "closing_headline": "Bigger was not better.",
        "genre_ids": [14], "vote_avg_gte": 7.0, "vote_count_gte": 500,
    },
    {
        "slug": "action_2010s",
        "title": "Five 2010s action films where the choreography tells the story",
        "subtitle": "movement as meaning.",
        "category": "ACTION LIST",
        "caption": "Five action films from the 2010s where how the body moves is what the film is actually about. Sources via TMDB.",
        "closing_headline": "Action is a director's medium.",
        "genre_ids": [28], "year_gte": 2010, "year_lte": 2019, "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },

    # ------------------------------------------------------------------ #
    # Language / country                                                   #
    # ------------------------------------------------------------------ #
    {
        "slug": "japanese_essential",
        "title": "Five Japanese films that make everything else feel slightly less precise",
        "subtitle": "a cinema unlike any other.",
        "category": "WORLD CINEMA",
        "caption": "Five Japanese films that set a standard of craft and intention that is difficult to match. Sources via TMDB.",
        "closing_headline": "There is a reason it is studied everywhere.",
        "original_language": "ja", "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "korean_essential",
        "title": "Five Korean films from the decade Korea rewrote what cinema could do",
        "subtitle": "beyond parasite. long before parasite.",
        "category": "WORLD CINEMA",
        "caption": "Five Korean films from the era when the industry was building toward something the world eventually noticed. Sources via TMDB.",
        "closing_headline": "The breakthrough was not a surprise to anyone paying attention.",
        "original_language": "ko", "vote_avg_gte": 7.2, "vote_count_gte": 500,
    },
    {
        "slug": "french_essential",
        "title": "Five French films that are nothing like what you think French cinema is",
        "subtitle": "not intellectual. not slow. not difficult.",
        "category": "WORLD CINEMA",
        "caption": "Five French films that undo the stereotype. Sources via TMDB.",
        "closing_headline": "The reputation is not the cinema.",
        "original_language": "fr", "vote_avg_gte": 7.3, "vote_count_gte": 500,
    },
    {
        "slug": "italian_essential",
        "title": "Five Italian films from the era when Italian cinema was better than everyone else's",
        "subtitle": "the 60s and 70s. theirs.",
        "category": "WORLD CINEMA",
        "caption": "Five Italian films from the decades Italy led cinema in style, ambition, and craft. Sources via TMDB.",
        "closing_headline": "Style is not superficial.",
        "original_language": "it", "vote_avg_gte": 7.3, "vote_count_gte": 400,
    },
    {
        "slug": "spanish_essential",
        "title": "Five Spanish films from a cinema that runs entirely on controlled fury",
        "subtitle": "something is always at stake.",
        "category": "WORLD CINEMA",
        "caption": "Five Spanish films with an intensity that comes from a specific cultural tension. Sources via TMDB.",
        "closing_headline": "Spain makes films like it means it.",
        "original_language": "es", "vote_avg_gte": 7.2, "vote_count_gte": 400,
    },
    {
        "slug": "german_essential",
        "title": "Five German films where history is not the background — it is the entire point",
        "subtitle": "cinema as reckoning.",
        "category": "WORLD CINEMA",
        "caption": "Five German films that carry the weight of the 20th century and turn it into art. Sources via TMDB.",
        "closing_headline": "No country processes its history through film like Germany.",
        "original_language": "de", "vote_avg_gte": 7.3, "vote_count_gte": 400,
    },
    {
        "slug": "scandinavian_films",
        "title": "Five Scandinavian films that use cold and dark the way other directors use close-ups",
        "subtitle": "long winters make extraordinary cinema.",
        "category": "WORLD CINEMA",
        "caption": "Five Scandinavian films where the landscape is doing as much work as the actors. Sources via TMDB.",
        "closing_headline": "The cold gets inside you.",
        "original_language": "sv", "vote_avg_gte": 7.0, "vote_count_gte": 300,
    },
    {
        "slug": "chinese_essential",
        "title": "Five Chinese films from a cinema the world has barely started paying attention to",
        "subtitle": "the scale of what exists is staggering.",
        "category": "WORLD CINEMA",
        "caption": "Five Chinese films from a body of work that rarely gets the international attention it deserves. Sources via TMDB.",
        "closing_headline": "There is a canon here. Start building yours.",
        "original_language": "zh", "vote_avg_gte": 7.2, "vote_count_gte": 300,
    },

    # ------------------------------------------------------------------ #
    # Decade retrospectives                                                 #
    # ------------------------------------------------------------------ #
    {
        "slug": "best_of_60s",
        "title": "Five films from the 60s that solved problems cinema is still wrestling with",
        "subtitle": "sixty years ahead.",
        "category": "FILM LIST",
        "caption": "Five films from the 1960s that found formal and narrative solutions nobody has fully bettered. Sources via TMDB.",
        "closing_headline": "Sixty years ago and still not caught up to.",
        "year_gte": 1960, "year_lte": 1969, "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "best_of_70s",
        "title": "Five films from the 70s when Hollywood accidentally made its best work",
        "subtitle": "the studio system was broken. the films were perfect.",
        "category": "FILM LIST",
        "caption": "Five films from the 1970s — the decade American cinema was at its most free and most uncomfortable. Sources via TMDB.",
        "closing_headline": "It will not happen again.",
        "year_gte": 1970, "year_lte": 1979, "vote_avg_gte": 7.5, "vote_count_gte": 1000,
    },
    {
        "slug": "best_of_2010s",
        "title": "Five films from the 2010s the decade has not caught up to yet",
        "subtitle": "the verdict is still forming.",
        "category": "FILM LIST",
        "caption": "Five films from the 2010s that were either ignored or misread at the time. Sources via TMDB.",
        "closing_headline": "Give it ten more years.",
        "year_gte": 2010, "year_lte": 2019, "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "recent_overlooked",
        "title": "Five films from the last five years that the algorithm buried",
        "subtitle": "the recommendation engine failed you.",
        "category": "FILM LIST",
        "caption": "Five films from the last five years that never found their audience. They should have. Sources via TMDB.",
        "closing_headline": "You missed them. Fix that.",
        "year_gte": 2019, "vote_avg_gte": 7.2, "vote_count_gte": 500, "vote_count_lte": 5000,
    },

    # ------------------------------------------------------------------ #
    # Mood / occasion                                                      #
    # ------------------------------------------------------------------ #
    {
        "slug": "films_that_will_make_you_cry",
        "title": "Five films where the sadness is earned and you do not resent it",
        "subtitle": "catharsis is not manipulation.",
        "category": "DRAMA LIST",
        "caption": "Five films that make you cry because they have done the work to deserve it. Sources via TMDB.",
        "closing_headline": "You were warned. You watched anyway.",
        "genre_ids": [18], "vote_avg_gte": 7.5, "vote_count_gte": 3000,
    },
    {
        "slug": "films_for_a_bad_day",
        "title": "Five films that reframe a bad day rather than hiding from it",
        "subtitle": "not escapism. perspective.",
        "category": "FILM LIST",
        "caption": "Five films that make you feel differently about what you are going through — not by pretending it isn't there. Sources via TMDB.",
        "closing_headline": "Things look different after.",
        "genre_ids": [35, 18], "vote_avg_gte": 7.3, "vote_count_gte": 2000,
    },
    {
        "slug": "films_for_insomnia",
        "title": "Five films that only work past midnight",
        "subtitle": "something about the hour makes them right.",
        "category": "FILM LIST",
        "caption": "Five films that exist in a register that only late nights understand. Sources via TMDB.",
        "closing_headline": "You will not regret staying up.",
        "genre_ids": [53, 9648], "vote_avg_gte": 7.0,
    },
    {
        "slug": "films_that_will_unsettle_you",
        "title": "Five films that do not leave you when the credits roll",
        "subtitle": "you will be thinking about these for days.",
        "category": "THRILLER LIST",
        "caption": "Five films that settle into you and stay there. Sources via TMDB.",
        "closing_headline": "You asked for this.",
        "genre_ids": [53, 27], "vote_avg_gte": 7.2,
    },
    {
        "slug": "comfort_films",
        "title": "Five films that make you feel better not because they lie to you but because they are kind",
        "subtitle": "kindness is harder to make than drama.",
        "category": "FILM LIST",
        "caption": "Five films that are genuinely restorative. Not shallow. Not dishonest. Just kind. Sources via TMDB.",
        "closing_headline": "Sometimes you just need this.",
        "genre_ids": [35, 10751], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "films_about_grief",
        "title": "Five films that treat grief with the weight it actually deserves",
        "subtitle": "they do not try to fix it.",
        "category": "DRAMA LIST",
        "caption": "Five films where loss is handled honestly, without resolution, without consolation prize. Sources via TMDB.",
        "closing_headline": "Loss, on screen, done right.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },

    # ------------------------------------------------------------------ #
    # Style / technique                                                    #
    # ------------------------------------------------------------------ #
    {
        "slug": "one_location_films",
        "title": "Five films where one room or one building contains the entire world",
        "subtitle": "constraint is creative fuel.",
        "category": "FILM LIST",
        "caption": "Five films that prove the whole world fits in a single location. Sources via TMDB.",
        "closing_headline": "Everything you need is already here.",
        "genre_ids": [53, 18], "vote_avg_gte": 7.0,
    },
    {
        "slug": "true_story_films",
        "title": "Five films where the true story is more extraordinary than anything a script could invent",
        "subtitle": "you could not make this up.",
        "category": "FILM LIST",
        "caption": "Five films based on real events that are more astonishing for being real. Sources via TMDB.",
        "closing_headline": "It actually happened.",
        "genre_ids": [36, 80, 18], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "silent_era_masterworks",
        "title": "Five silent films that communicate more without dialogue than most films do with it",
        "subtitle": "silence is not absence.",
        "category": "FILM LIST",
        "caption": "Five silent films that found ways to express what words cannot. Sources via TMDB.",
        "closing_headline": "Everything language cannot do, images can.",
        "year_lte": 1935, "vote_avg_gte": 7.5, "vote_count_gte": 200,
    },
    {
        "slug": "long_films_worth_it",
        "title": "Five films over three hours where the runtime is the point",
        "subtitle": "you need all of it.",
        "category": "FILM LIST",
        "caption": "Five films where the length is inseparable from what the film is trying to do. Sources via TMDB.",
        "closing_headline": "Block out the day.",
        "runtime_gte": 180, "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "first_films",
        "title": "Five debut films so fully formed they make other directors' careers look like warm-up acts",
        "subtitle": "arrived complete.",
        "category": "FILM LIST",
        "caption": "Five filmmakers who got it entirely right on the first attempt. Sources via TMDB.",
        "closing_headline": "There was no learning curve.",
        "vote_avg_gte": 7.5, "vote_count_gte": 1000,
        "genre_ids": [18, 53, 80],
    },
    {
        "slug": "road_movies",
        "title": "Five road movies where the destination is irrelevant and the journey dismantles something",
        "subtitle": "movement as transformation.",
        "category": "FILM LIST",
        "caption": "Five road movies that use travel to take apart the person making the trip. Sources via TMDB.",
        "closing_headline": "You arrive somewhere different.",
        "genre_ids": [12, 18], "vote_avg_gte": 7.2,
    },

    # ------------------------------------------------------------------ #
    # Topic-based                                                          #
    # ------------------------------------------------------------------ #
    {
        "slug": "films_about_ai",
        "title": "Five films about artificial intelligence that were describing the present before we knew it",
        "subtitle": "fiction that became non-fiction.",
        "category": "SCI-FI LIST",
        "caption": "Five films about AI that anticipated where we are now. Watch them differently this time. Sources via TMDB.",
        "closing_headline": "They tried to tell us.",
        "genre_ids": [878], "vote_avg_gte": 7.0,
    },
    {
        "slug": "heist_films",
        "title": "Five heist films where the pleasure is watching competent people solve a hard problem",
        "subtitle": "competence is the most watchable thing.",
        "category": "CRIME LIST",
        "caption": "Five heist films where the mechanics of the job are what make it work. Sources via TMDB.",
        "closing_headline": "A good plan is a beautiful thing.",
        "genre_ids": [80, 53], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "space_films",
        "title": "Five space films that understand what is actually out there is stranger than the fiction",
        "subtitle": "the universe does not need embellishment.",
        "category": "SCI-FI LIST",
        "caption": "Five space films that take reality as their starting point and let that be enough. Sources via TMDB.",
        "closing_headline": "The real thing is more astonishing.",
        "genre_ids": [878, 12], "vote_avg_gte": 7.0, "vote_count_gte": 1000,
    },
    {
        "slug": "prison_films",
        "title": "Five prison films where captivity is a metaphor for something much harder to escape",
        "subtitle": "the walls are always symbolic.",
        "category": "DRAMA LIST",
        "caption": "Five prison films that use confinement to say something about what freedom actually means. Sources via TMDB.",
        "closing_headline": "The real prison is somewhere else.",
        "genre_ids": [18, 80], "vote_avg_gte": 7.3,
    },
    {
        "slug": "sports_films",
        "title": "Five sports films for people with no interest in sport whatsoever",
        "subtitle": "they are not really about sport.",
        "category": "DRAMA LIST",
        "caption": "Five sports films that use competition as a lens for something bigger. Sources via TMDB.",
        "closing_headline": "You do not have to care about the game.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "political_films",
        "title": "Five political films that show you how power works without telling you what to think about it",
        "subtitle": "they just show you.",
        "category": "DRAMA LIST",
        "caption": "Five political films that describe the mechanics of power without a moral instruction attached. Sources via TMDB.",
        "closing_headline": "An informed audience is a dangerous audience.",
        "genre_ids": [36, 18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "addiction_films",
        "title": "Five films about addiction that are honest about what it looks like from the inside",
        "subtitle": "no glamour. no redemption arc required.",
        "category": "DRAMA LIST",
        "caption": "Five films about addiction that do not flinch from what it actually is. Sources via TMDB.",
        "closing_headline": "This is what it looks like.",
        "genre_ids": [18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "memory_identity_films",
        "title": "Five films that interrogate how unreliable the self you have constructed actually is",
        "subtitle": "you are not who you think you are.",
        "category": "FILM LIST",
        "caption": "Five films where memory, identity, and the stories we tell ourselves are the subject. Sources via TMDB.",
        "closing_headline": "Memory is unreliable. Cinema proves it.",
        "genre_ids": [53, 18, 878], "vote_avg_gte": 7.3,
    },
    {
        "slug": "war_antiwar",
        "title": "Five war films that use the genre to make the strongest possible case against war",
        "subtitle": "the genre as protest.",
        "category": "WAR LIST",
        "caption": "Five war films that turn the genre against itself. Sources via TMDB.",
        "closing_headline": "The camera is always making an argument.",
        "genre_ids": [10752, 18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "survival_films",
        "title": "Five survival films where the real question is who you become, not whether you survive",
        "subtitle": "endurance is the subject. survival is the excuse.",
        "category": "FILM LIST",
        "caption": "Five survival films where the physical ordeal is a way of examining something about character. Sources via TMDB.",
        "closing_headline": "Survival is a choice about who to be.",
        "genre_ids": [12, 18, 53], "vote_avg_gte": 7.2, "vote_count_gte": 1000,
    },
    {
        "slug": "journalism_films",
        "title": "Five films about journalism from the era when it worked",
        "subtitle": "what accountability used to look like.",
        "category": "DRAMA LIST",
        "caption": "Five films about journalism that remind you what it was for. Sources via TMDB.",
        "closing_headline": "The press used to be something.",
        "genre_ids": [18, 36], "vote_avg_gte": 7.2,
    },
    {
        "slug": "family_drama",
        "title": "Five films about family that refuse to resolve what families never resolve",
        "subtitle": "complicated people. complicated love.",
        "category": "DRAMA LIST",
        "caption": "Five films about family that resist the tidy ending because families never have one. Sources via TMDB.",
        "closing_headline": "Families are not tidy.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "coming_of_age",
        "title": "Five coming-of-age films where becoming a person does not feel triumphant",
        "subtitle": "growing up costs something.",
        "category": "DRAMA LIST",
        "caption": "Five coming-of-age films that treat adolescence as loss as much as discovery. Sources via TMDB.",
        "closing_headline": "Everyone is still becoming. It does not get easier.",
        "genre_ids": [18, 35], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },

    # ------------------------------------------------------------------ #
    # Director spotlights                                                   #
    # ------------------------------------------------------------------ #
    {
        "slug": "kubrick_retrospective",
        "title": "Five Kubrick films ranked by how long they stay in your head after",
        "subtitle": "from unsettling to permanent.",
        "category": "DIRECTOR LIST",
        "caption": "Five Stanley Kubrick films. Each one a controlled act of provocation designed to outlast its runtime. Sources via TMDB.",
        "closing_headline": "There will never be another Kubrick.",
        "with_people": "240", "vote_avg_gte": 7.5,
    },
    {
        "slug": "scorsese_retrospective",
        "title": "Five Scorsese films that prove Goodfellas is not his best",
        "subtitle": "there is a whole filmography out there.",
        "category": "DIRECTOR LIST",
        "caption": "Five Martin Scorsese films that get overshadowed by the obvious ones. Sources via TMDB.",
        "closing_headline": "He made more than you think. And it is better.",
        "with_people": "1032", "vote_avg_gte": 7.2,
    },
    {
        "slug": "coen_brothers",
        "title": "Five Coen Brothers films ordered by how funny the tragedy actually is",
        "subtitle": "they find it funny. so will you, eventually.",
        "category": "DIRECTOR LIST",
        "caption": "Five films from the Coen Brothers. Bleaker, funnier, smarter than everyone else. Sources via TMDB.",
        "closing_headline": "Nobody does it like them.",
        "with_people": "1223,1224", "vote_avg_gte": 7.2,
    },
    {
        "slug": "wong_kar_wai",
        "title": "Five Wong Kar-wai films about people who cannot stop looking backwards",
        "subtitle": "every frame is about missing someone.",
        "category": "DIRECTOR LIST",
        "caption": "Five films from Wong Kar-wai. No one films longing the way he does. Sources via TMDB.",
        "closing_headline": "Memory and desire. On film.",
        "with_people": "12453", "vote_avg_gte": 7.3,
    },
    {
        "slug": "lynch_films",
        "title": "Five David Lynch films from most accessible to completely inexplicable",
        "subtitle": "start here, then surrender.",
        "category": "DIRECTOR LIST",
        "caption": "Five David Lynch films. He is not trying to confuse you. He is trying to show you something real. Sources via TMDB.",
        "closing_headline": "Logic is overrated.",
        "with_people": "5765", "vote_avg_gte": 7.0,
    },
    {
        "slug": "kurosawa_films",
        "title": "Five Kurosawa films that exist underneath every action film you have ever seen",
        "subtitle": "you have already seen these. you just do not know it.",
        "category": "DIRECTOR LIST",
        "caption": "Five Akira Kurosawa films. The blueprint for most of the action cinema you love. Sources via TMDB.",
        "closing_headline": "The original. All others are cover versions.",
        "with_people": "7175", "vote_avg_gte": 7.5,
    },
    {
        "slug": "tarkovsky_films",
        "title": "Five Tarkovsky films that take as long as they need and give back more than you put in",
        "subtitle": "slow cinema. permanent effect.",
        "category": "DIRECTOR LIST",
        "caption": "Five Andrei Tarkovsky films. Deliberately slow. Permanently affecting. Sources via TMDB.",
        "closing_headline": "Take your time. He did.",
        "with_people": "12432", "vote_avg_gte": 7.5,
    },
    {
        "slug": "fassbinder_films",
        "title": "Five Fassbinder films from the man who made 40 in 13 years and most were extraordinary",
        "subtitle": "furious, prolific, essential.",
        "category": "DIRECTOR LIST",
        "caption": "Five Rainer Werner Fassbinder films. He made 40 in 13 years. These are the ones to start with. Sources via TMDB.",
        "closing_headline": "A filmmaker who burned too bright and too fast.",
        "with_people": "7232", "vote_avg_gte": 7.2,
    },

    # ------------------------------------------------------------------ #
    # Award + critical recognition                                         #
    # ------------------------------------------------------------------ #
    {
        "slug": "palme_dor_winners",
        "title": "Five times Cannes gave the Palme d'Or to exactly the right film",
        "subtitle": "the jury was correct.",
        "category": "FILM LIST",
        "caption": "Five Palme d'Or winners that deserved it unambiguously. Sources via TMDB.",
        "closing_headline": "Sometimes the prize goes to the right person.",
        "vote_avg_gte": 7.5, "vote_count_gte": 2000,
        "genre_ids": [18, 53, 80],
    },
    {
        "slug": "overlooked_oscar_winners",
        "title": "Five Best Picture winners that have been eclipsed by other films from their own year",
        "subtitle": "the academy moved on. these deserve better.",
        "category": "FILM LIST",
        "caption": "Five Best Picture winners that should not be forgotten just because something else from the same year was more talked about. Sources via TMDB.",
        "closing_headline": "The statue was right. The conversation was not.",
        "vote_avg_gte": 7.0, "vote_count_gte": 3000,
        "genre_ids": [18, 36],
    },
    {
        "slug": "cult_classics",
        "title": "Five cult films that earned the cult following through quality, not irony",
        "subtitle": "not bad. not misunderstood. genuinely good.",
        "category": "FILM LIST",
        "caption": "Five cult films with followings that exist because the films are right, not because they are wrong in an enjoyable way. Sources via TMDB.",
        "closing_headline": "Some films take time to find their audience. These found theirs.",
        "vote_avg_gte": 7.0, "vote_count_gte": 1000,
        "genre_ids": [53, 878, 27],
    },
    {
        "slug": "films_critics_hated",
        "title": "Five films critics dismissed that time has proved them completely wrong about",
        "subtitle": "the audience wins sometimes.",
        "category": "FILM LIST",
        "caption": "Five films where the critical reception at the time was confidently, embarrassingly incorrect. Sources via TMDB.",
        "closing_headline": "The reviews aged badly. The films did not.",
        "vote_avg_gte": 7.0, "vote_count_gte": 5000,
    },

    # ------------------------------------------------------------------ #
    # More genre combos                                                    #
    # ------------------------------------------------------------------ #
    {
        "slug": "neo_noir",
        "title": "Five neo-noir films built on the assumption that everybody lies and nobody wins",
        "subtitle": "the moral universe is flat.",
        "category": "CRIME LIST",
        "caption": "Five neo-noir films that inherit the genre's bleakest premise and deliver it with modern dread. Sources via TMDB.",
        "closing_headline": "The darkness is comfortable here.",
        "genre_ids": [80, 53], "year_gte": 1990, "vote_avg_gte": 7.2,
    },
    {
        "slug": "psychological_horror",
        "title": "Five horror films where the monster never appears and that is why they work",
        "subtitle": "the scariest thing is what you imagine.",
        "category": "HORROR LIST",
        "caption": "Five horror films where the horror is interior. No jump scares. No creature. Pure dread. Sources via TMDB.",
        "closing_headline": "You will question yourself after.",
        "genre_ids": [27, 53], "vote_avg_gte": 7.0,
    },
    {
        "slug": "arthouse_accessible",
        "title": "Five arthouse films that reward patience without demanding a film degree",
        "subtitle": "slow is not the same as obscure.",
        "category": "FILM LIST",
        "caption": "Five arthouse films that meet you halfway without dumbing down. Sources via TMDB.",
        "closing_headline": "You do not need preparation. Just time.",
        "vote_avg_gte": 7.5, "vote_count_gte": 500,
        "genre_ids": [18],
    },
    {
        "slug": "crime_masterpieces",
        "title": "Five crime films that do the work of serious literature using genre as cover",
        "subtitle": "the genre as a delivery mechanism.",
        "category": "CRIME LIST",
        "caption": "Five crime films that use the genre to carry ideas a literary novel would struggle to move. Sources via TMDB.",
        "closing_headline": "Crime fiction is serious fiction.",
        "genre_ids": [80], "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "black_comedy_essential",
        "title": "Five black comedies that get darker and funnier the older you get",
        "subtitle": "age gives you permission to laugh.",
        "category": "COMEDY LIST",
        "caption": "Five black comedies that reveal new layers of bleakness and brilliance on every rewatch. Sources via TMDB.",
        "closing_headline": "It gets funnier as you get older. Worryingly.",
        "genre_ids": [35, 53], "vote_avg_gte": 7.3,
    },
    {
        "slug": "female_directors",
        "title": "Five films directed by women that belong in any serious conversation about the art form",
        "subtitle": "not a list. a correction.",
        "category": "FILM LIST",
        "caption": "Five films directed by women that the canon underweights. Sources via TMDB.",
        "closing_headline": "Half of cinema was missing. These found it.",
        "vote_avg_gte": 7.2, "vote_count_gte": 500,
        "genre_ids": [18, 53],
    },
    {
        "slug": "music_films",
        "title": "Five music films that capture what it feels like from the inside rather than watching from outside",
        "subtitle": "not biopics. the actual experience.",
        "category": "MUSIC LIST",
        "caption": "Five films about music that capture the interior experience rather than the biography. Sources via TMDB.",
        "closing_headline": "Some things only music can say. These films come close.",
        "genre_ids": [10402, 18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "environmental_films",
        "title": "Five films about the natural world that make the news make sense",
        "subtitle": "context the headlines skip.",
        "category": "DOCUMENTARY LIST",
        "caption": "Five films that explain what is at stake in a way the news cycle cannot. Sources via TMDB.",
        "closing_headline": "Watch now. Act later.",
        "genre_ids": [99], "vote_avg_gte": 7.2,
    },
    {
        "slug": "anthology_films",
        "title": "Five anthology films where every segment earns its place and the format is the point",
        "subtitle": "the short form is underrated.",
        "category": "FILM LIST",
        "caption": "Five anthology films where the segmented structure does something a single story could not. Sources via TMDB.",
        "closing_headline": "The short form contains multitudes.",
        "genre_ids": [18, 35, 27], "vote_avg_gte": 7.2,
    },

    # ------------------------------------------------------------------ #
    # Genuinely niche angles — criteria no algorithm would generate        #
    # ------------------------------------------------------------------ #
    {
        "slug": "villain_best_performance",
        "title": "Five films where the villain gives the best performance in the entire cast",
        "subtitle": "sometimes the wrong person is more interesting.",
        "category": "FILM LIST",
        "caption": "Five films where the antagonist is the most compelling presence on screen. Sources via TMDB.",
        "closing_headline": "The villain always knows something the hero does not.",
        "genre_ids": [53, 80, 27], "vote_avg_gte": 7.3, "vote_count_gte": 2000,
    },
    {
        "slug": "box_office_failures_now_essential",
        "title": "Five films that bombed on release and are now considered essential",
        "subtitle": "the audience was wrong the first time.",
        "category": "FILM LIST",
        "caption": "Five films the original audience rejected and subsequent audiences made indispensable. Sources via TMDB.",
        "closing_headline": "The first take is not always the right one.",
        "year_lte": 2015, "vote_avg_gte": 7.3, "vote_count_gte": 3000,
        "genre_ids": [18, 53, 878],
    },
    {
        "slug": "con_artist_films",
        "title": "Five films about con artists where you root for the con",
        "subtitle": "morality is negotiable when the craft is this good.",
        "category": "CRIME LIST",
        "caption": "Five films about deception where the filmmaker makes you complicit in the swindle. Sources via TMDB.",
        "closing_headline": "You knew you were being played. You did not mind.",
        "genre_ids": [80, 35, 53], "vote_avg_gte": 7.2, "vote_count_gte": 1000,
    },
    {
        "slug": "obsession_films",
        "title": "Five films about obsession where the film makes you understand the obsession",
        "subtitle": "not cautionary tales. genuine portraits.",
        "category": "DRAMA LIST",
        "caption": "Five films about obsession that take the obsession seriously rather than diagnosing it from the outside. Sources via TMDB.",
        "closing_headline": "You come away understanding something you probably should not.",
        "genre_ids": [18, 53, 9648], "vote_avg_gte": 7.3,
    },
    {
        "slug": "single_day_films",
        "title": "Five films that take place over a single day and use every hour",
        "subtitle": "twenty-four hours is enough for a lifetime.",
        "category": "FILM LIST",
        "caption": "Five films that compress a world into one day without feeling rushed or contrived. Sources via TMDB.",
        "closing_headline": "A day is enough for everything to change.",
        "genre_ids": [18, 53, 35], "vote_avg_gte": 7.2, "vote_count_gte": 1000,
    },
    {
        "slug": "city_as_character",
        "title": "Five films where the city is doing as much work as any of the actors",
        "subtitle": "place is not setting. it is character.",
        "category": "FILM LIST",
        "caption": "Five films where the city shapes events as actively as any human in the story. Sources via TMDB.",
        "closing_headline": "You leave knowing the city.",
        "genre_ids": [18, 80, 53], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "failure_films",
        "title": "Five films about failure that refuse to make it redemptive",
        "subtitle": "sometimes things do not turn around.",
        "category": "DRAMA LIST",
        "caption": "Five films where failure is the subject and the ending does not fix it. Sources via TMDB.",
        "closing_headline": "Failure is not always a beginning.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 500,
    },
    {
        "slug": "films_better_on_rewatch",
        "title": "Five films that work better the second time once you know what they are doing",
        "subtitle": "the first watch is the setup.",
        "category": "FILM LIST",
        "caption": "Five films where knowing what happens changes everything about how you watch them. Sources via TMDB.",
        "closing_headline": "You missed most of it the first time.",
        "genre_ids": [53, 9648, 18], "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "films_made_under_pressure",
        "title": "Five films made on almost no money that you would never know were cheap",
        "subtitle": "constraint is creative fuel.",
        "category": "FILM LIST",
        "caption": "Five films where the budget limitations became part of the style. Sources via TMDB.",
        "closing_headline": "Money is the least interesting resource.",
        "year_gte": 1990, "vote_avg_gte": 7.3, "vote_count_gte": 500,
        "genre_ids": [18, 53, 27],
    },
    {
        "slug": "ending_reframes_everything",
        "title": "Five films where the ending retroactively changes everything that came before it",
        "subtitle": "go in blind. come out recalibrated.",
        "category": "FILM LIST",
        "caption": "Five films where the final scene forces you to reassemble everything you just watched. Sources via TMDB.",
        "closing_headline": "Rewatch from the beginning. You missed everything.",
        "genre_ids": [53, 9648, 18, 878], "vote_avg_gte": 7.5, "vote_count_gte": 3000,
    },
    {
        "slug": "films_about_work",
        "title": "Five films where what people do for money is what the film is actually about",
        "subtitle": "labour as character study.",
        "category": "DRAMA LIST",
        "caption": "Five films where the job is not backdrop but the entire subject. Sources via TMDB.",
        "closing_headline": "What you do all day is who you are.",
        "genre_ids": [18, 80], "vote_avg_gte": 7.3, "vote_count_gte": 500,
    },
    {
        "slug": "films_without_villains",
        "title": "Five films with no villain where the absence of one is more disturbing than having one",
        "subtitle": "nobody is wrong. everything is terrible.",
        "category": "DRAMA LIST",
        "caption": "Five films where the tragedy is structural rather than caused by a bad person, which makes it harder to resolve. Sources via TMDB.",
        "closing_headline": "No one to blame. That is the point.",
        "genre_ids": [18], "vote_avg_gte": 7.4, "vote_count_gte": 1000,
    },

]
