"""Theme pool for auto-generated list carousel packs.

Each theme maps to a TMDB Discover query. `generate_list_packs.py` picks
random unused themes weekly, fetches films, and writes complete packs to
data/ledgers/generated_list_packs.jsonl.

With 80+ themes covering genres, eras, countries, moods, directors, and
styles, the system runs for over a year before cycling - and even then the
films will be different (posted_ids dedup ensures no film repeats).

TMDB genre IDs reference:
  28=Action  12=Adventure  16=Animation  35=Comedy  80=Crime
  99=Documentary  18=Drama  14=Fantasy  36=History  27=Horror
  9648=Mystery  10749=Romance  878=Sci-Fi  53=Thriller  10752=War  37=Western
"""
from __future__ import annotations

THEMES: list[dict] = [

    # ------------------------------------------------------------------ #
    # Genre + era                                                          #
    # ------------------------------------------------------------------ #
    {
        "slug": "horror_80s",
        "title": "Five horror films from the 80s that still work",
        "subtitle": "no nostalgia required.",
        "category": "HORROR LIST",
        "caption": "Five horror films from the 80s that still genuinely unsettle. No nostalgia, just craft. Sources via TMDB.",
        "closing_headline": "Watch with the lights on.",
        "genre_ids": [27], "year_gte": 1980, "year_lte": 1989, "vote_avg_gte": 6.8,
    },
    {
        "slug": "horror_90s",
        "title": "Five horror films from the 90s worth revisiting",
        "subtitle": "the decade horror got weird.",
        "category": "HORROR LIST",
        "caption": "Five horror films from the 90s. A decade that blurred the line between genre and art. Sources via TMDB.",
        "closing_headline": "You will not sleep well.",
        "genre_ids": [27], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 6.8,
    },
    {
        "slug": "crime_70s",
        "title": "Five crime films from the 70s that set the standard",
        "subtitle": "before everything got polished.",
        "category": "CRIME LIST",
        "caption": "Five crime films from the 70s. Gritty, human, and still unsurpassed. Sources via TMDB.",
        "closing_headline": "The golden era of crime cinema.",
        "genre_ids": [80], "year_gte": 1970, "year_lte": 1979, "vote_avg_gte": 7.0,
    },
    {
        "slug": "sci_fi_80s",
        "title": "Five sci-fi films from the 80s that predicted everything",
        "subtitle": "they were right.",
        "category": "SCI-FI LIST",
        "caption": "Five sci-fi films from the 80s that saw it coming. Sources via TMDB.",
        "closing_headline": "They warned us.",
        "genre_ids": [878], "year_gte": 1980, "year_lte": 1989, "vote_avg_gte": 7.0,
    },
    {
        "slug": "sci_fi_90s",
        "title": "Five sci-fi films from the 90s that hold up",
        "subtitle": "the decade that built the matrix.",
        "category": "SCI-FI LIST",
        "caption": "Five sci-fi films from the 90s. The decade that rewired what science fiction could be. Sources via TMDB.",
        "closing_headline": "Reality optional.",
        "genre_ids": [878], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 7.0,
    },
    {
        "slug": "thriller_90s",
        "title": "Five thrillers from the 90s that kept you guessing",
        "subtitle": "before every twist was spoiled.",
        "category": "THRILLER LIST",
        "caption": "Five thrillers from the 90s. The twist era, done properly. Sources via TMDB.",
        "closing_headline": "Go in blind.",
        "genre_ids": [53], "year_gte": 1990, "year_lte": 1999, "vote_avg_gte": 7.0,
    },
    {
        "slug": "drama_2000s",
        "title": "Five dramas from the 2000s that were ahead of their time",
        "subtitle": "they flopped. critics were wrong.",
        "category": "DRAMA LIST",
        "caption": "Five dramas from the 2000s that deserved more. Some flopped, some were ignored. All worth your time. Sources via TMDB.",
        "closing_headline": "Reappraise everything.",
        "genre_ids": [18], "year_gte": 2000, "year_lte": 2009, "vote_avg_gte": 7.2,
    },
    {
        "slug": "animation_all_time",
        "title": "Five animated films that are not for children",
        "subtitle": "the ones adults need more.",
        "category": "ANIMATION LIST",
        "caption": "Five animated films that operate on a completely different level. Sources via TMDB.",
        "closing_headline": "Animation is not a genre.",
        "genre_ids": [16], "vote_avg_gte": 7.5, "vote_count_gte": 1000,
    },
    {
        "slug": "western_all_time",
        "title": "Five westerns that transcend the genre",
        "subtitle": "not about cowboys. about everything.",
        "category": "WESTERN LIST",
        "caption": "Five westerns that use the setting to say something bigger. Sources via TMDB.",
        "closing_headline": "The West is a state of mind.",
        "genre_ids": [37], "vote_avg_gte": 7.2,
    },
    {
        "slug": "documentary_essential",
        "title": "Five documentaries that will change how you think",
        "subtitle": "not comfortable viewing.",
        "category": "DOCUMENTARY LIST",
        "caption": "Five documentaries that reframe something you thought you understood. Sources via TMDB.",
        "closing_headline": "Watch and then do something about it.",
        "genre_ids": [99], "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "comedy_dark",
        "title": "Five dark comedies that make you laugh and wince",
        "subtitle": "the best kind of uncomfortable.",
        "category": "COMEDY LIST",
        "caption": "Five dark comedies that earn every uncomfortable laugh. Sources via TMDB.",
        "closing_headline": "It is fine to laugh.",
        "genre_ids": [35], "vote_avg_gte": 7.2, "vote_count_gte": 800,
    },
    {
        "slug": "mystery_essential",
        "title": "Five mystery films where the reveal actually earns it",
        "subtitle": "no cheap twists.",
        "category": "MYSTERY LIST",
        "caption": "Five mystery films where the ending is worth the wait. Sources via TMDB.",
        "closing_headline": "Go in knowing nothing.",
        "genre_ids": [9648], "vote_avg_gte": 7.2,
    },
    {
        "slug": "history_films",
        "title": "Five historical films that got it mostly right",
        "subtitle": "research optional, but rewarding.",
        "category": "HISTORY LIST",
        "caption": "Five historical films that take the subject seriously. Sources via TMDB.",
        "closing_headline": "History is stranger than fiction.",
        "genre_ids": [36], "vote_avg_gte": 7.0,
    },
    {
        "slug": "fantasy_underrated",
        "title": "Five fantasy films that never got their due",
        "subtitle": "buried under blockbusters.",
        "category": "FANTASY LIST",
        "caption": "Five fantasy films that deserved a bigger audience. Sources via TMDB.",
        "closing_headline": "Imagination is underrated.",
        "genre_ids": [14], "vote_avg_gte": 7.0, "vote_count_gte": 500,
    },
    {
        "slug": "action_2010s",
        "title": "Five action films from the 2010s with actual craft",
        "subtitle": "not all CGI.",
        "category": "ACTION LIST",
        "caption": "Five action films from the 2010s that put work into the craft. Sources via TMDB.",
        "closing_headline": "Action is a director's medium.",
        "genre_ids": [28], "year_gte": 2010, "year_lte": 2019, "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },

    # ------------------------------------------------------------------ #
    # Language / country                                                   #
    # ------------------------------------------------------------------ #
    {
        "slug": "japanese_essential",
        "title": "Five essential Japanese films",
        "subtitle": "a cinema unlike any other.",
        "category": "WORLD CINEMA",
        "caption": "Five Japanese films that are essential viewing. Start here. Sources via TMDB.",
        "closing_headline": "Japanese cinema is the best cinema.",
        "original_language": "ja", "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "korean_essential",
        "title": "Five Korean films worth your time",
        "subtitle": "beyond parasite.",
        "category": "WORLD CINEMA",
        "caption": "Five Korean films that prove the industry is producing some of the best cinema in the world. Sources via TMDB.",
        "closing_headline": "Korea is not a genre.",
        "original_language": "ko", "vote_avg_gte": 7.2, "vote_count_gte": 500,
    },
    {
        "slug": "french_essential",
        "title": "Five French films that are actually watchable",
        "subtitle": "no subtitles required. well, some.",
        "category": "WORLD CINEMA",
        "caption": "Five French films that work even if you have no interest in French cinema. Sources via TMDB.",
        "closing_headline": "The French were right.",
        "original_language": "fr", "vote_avg_gte": 7.3, "vote_count_gte": 500,
    },
    {
        "slug": "italian_essential",
        "title": "Five Italian films that defined European cinema",
        "subtitle": "the decade the Italians led everything.",
        "category": "WORLD CINEMA",
        "caption": "Five Italian films that shaped how cinema looked and felt. Sources via TMDB.",
        "closing_headline": "Style is not superficial.",
        "original_language": "it", "vote_avg_gte": 7.3, "vote_count_gte": 400,
    },
    {
        "slug": "spanish_essential",
        "title": "Five Spanish films that deserve a global audience",
        "subtitle": "a cinema full of fury.",
        "category": "WORLD CINEMA",
        "caption": "Five Spanish films that are doing things no one else is. Sources via TMDB.",
        "closing_headline": "Spanish cinema is having its moment.",
        "original_language": "es", "vote_avg_gte": 7.2, "vote_count_gte": 400,
    },
    {
        "slug": "german_essential",
        "title": "Five German films that are impossible to forget",
        "subtitle": "history and ambition, combined.",
        "category": "WORLD CINEMA",
        "caption": "Five German films that carry the weight of history and turn it into art. Sources via TMDB.",
        "closing_headline": "Germany produces films like no one else.",
        "original_language": "de", "vote_avg_gte": 7.3, "vote_count_gte": 400,
    },
    {
        "slug": "scandinavian_films",
        "title": "Five Scandinavian films that will haunt you",
        "subtitle": "cold, dark, and brilliant.",
        "category": "WORLD CINEMA",
        "caption": "Five Scandinavian films. Long winters produce extraordinary cinema. Sources via TMDB.",
        "closing_headline": "The cold gets inside you.",
        "original_language": "sv", "vote_avg_gte": 7.0, "vote_count_gte": 300,
    },
    {
        "slug": "chinese_essential",
        "title": "Five Chinese films the world should have seen",
        "subtitle": "a staggering body of work.",
        "category": "WORLD CINEMA",
        "caption": "Five Chinese films that rarely get the international attention they deserve. Sources via TMDB.",
        "closing_headline": "A cinema just waiting to be discovered.",
        "original_language": "zh", "vote_avg_gte": 7.2, "vote_count_gte": 300,
    },

    # ------------------------------------------------------------------ #
    # Decade retrospectives                                                 #
    # ------------------------------------------------------------------ #
    {
        "slug": "best_of_60s",
        "title": "Five films from the 60s that still feel modern",
        "subtitle": "they solved things we are still solving.",
        "category": "FILM LIST",
        "caption": "Five films from the 1960s that solved problems cinema is still wrestling with. Sources via TMDB.",
        "closing_headline": "Sixty years ago and still ahead.",
        "year_gte": 1960, "year_lte": 1969, "vote_avg_gte": 7.5, "vote_count_gte": 500,
    },
    {
        "slug": "best_of_70s",
        "title": "Five films from the 70s that defined a decade",
        "subtitle": "Hollywood's greatest era.",
        "category": "FILM LIST",
        "caption": "Five films from the 1970s - arguably the richest decade in American cinema. Sources via TMDB.",
        "closing_headline": "Nothing before or since.",
        "year_gte": 1970, "year_lte": 1979, "vote_avg_gte": 7.5, "vote_count_gte": 1000,
    },
    {
        "slug": "best_of_2010s",
        "title": "Five films from the 2010s that will define the decade",
        "subtitle": "the verdict is still coming in.",
        "category": "FILM LIST",
        "caption": "Five films from the 2010s that will be studied for decades. Sources via TMDB.",
        "closing_headline": "The best of the decade, still settling.",
        "year_gte": 2010, "year_lte": 2019, "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "recent_overlooked",
        "title": "Five recent films that barely anyone saw",
        "subtitle": "the algorithm buried them.",
        "category": "FILM LIST",
        "caption": "Five films from the last five years that deserved ten times the audience. Sources via TMDB.",
        "closing_headline": "You missed them. Fix that.",
        "year_gte": 2019, "vote_avg_gte": 7.2, "vote_count_gte": 500, "vote_count_lte": 5000,
    },

    # ------------------------------------------------------------------ #
    # Mood / occasion                                                      #
    # ------------------------------------------------------------------ #
    {
        "slug": "films_that_will_make_you_cry",
        "title": "Five films designed to make you cry",
        "subtitle": "catharsis is underrated.",
        "category": "DRAMA LIST",
        "caption": "Five films that will make you cry in ways you did not expect. Sources via TMDB.",
        "closing_headline": "You have been warned.",
        "genre_ids": [18], "vote_avg_gte": 7.5, "vote_count_gte": 3000,
    },
    {
        "slug": "films_for_a_bad_day",
        "title": "Five films that make a bad day better",
        "subtitle": "not escapism. perspective.",
        "category": "FILM LIST",
        "caption": "Five films that reframe the world just enough. Sources via TMDB.",
        "closing_headline": "Things look different after.",
        "genre_ids": [35, 18], "vote_avg_gte": 7.3, "vote_count_gte": 2000,
    },
    {
        "slug": "films_for_insomnia",
        "title": "Five films to watch at 3am",
        "subtitle": "they fit the hour.",
        "category": "FILM LIST",
        "caption": "Five films that only work at 3am. Something about the hour makes them right. Sources via TMDB.",
        "closing_headline": "You will not regret staying up.",
        "genre_ids": [53, 9648], "vote_avg_gte": 7.0,
    },
    {
        "slug": "films_that_will_unsettle_you",
        "title": "Five films that will stay with you for days",
        "subtitle": "in the uncomfortable way.",
        "category": "THRILLER LIST",
        "caption": "Five films that do not leave you when the credits roll. Sources via TMDB.",
        "closing_headline": "You asked for this.",
        "genre_ids": [53, 27], "vote_avg_gte": 7.2,
    },
    {
        "slug": "comfort_films",
        "title": "Five films for when you need comfort",
        "subtitle": "genuinely restorative.",
        "category": "FILM LIST",
        "caption": "Five films that actually make you feel better. Not because they are shallow - because they are kind. Sources via TMDB.",
        "closing_headline": "Sometimes you just need this.",
        "genre_ids": [35, 10751], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "films_about_grief",
        "title": "Five films that understand grief",
        "subtitle": "they do not try to fix it.",
        "category": "DRAMA LIST",
        "caption": "Five films that treat grief with the weight it deserves. Sources via TMDB.",
        "closing_headline": "Loss, on screen, done right.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },

    # ------------------------------------------------------------------ #
    # Style / technique                                                    #
    # ------------------------------------------------------------------ #
    {
        "slug": "one_location_films",
        "title": "Five films set almost entirely in one location",
        "subtitle": "constraint breeds creativity.",
        "category": "FILM LIST",
        "caption": "Five films that prove you do not need the whole world. Just one room, one building, one idea. Sources via TMDB.",
        "closing_headline": "Everything you need is already here.",
        "genre_ids": [53, 18], "vote_avg_gte": 7.0,
    },
    {
        "slug": "true_story_films",
        "title": "Five films based on true stories that are stranger than fiction",
        "subtitle": "you could not make this up.",
        "category": "FILM LIST",
        "caption": "Five films based on real events that are more extraordinary than any script could produce. Sources via TMDB.",
        "closing_headline": "It actually happened.",
        "genre_ids": [36, 80, 18], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "silent_era_masterworks",
        "title": "Five silent films that still hold up",
        "subtitle": "no dialogue needed.",
        "category": "FILM LIST",
        "caption": "Five silent films that communicate more without words than most films do with them. Sources via TMDB.",
        "closing_headline": "Silence is not absence.",
        "year_lte": 1935, "vote_avg_gte": 7.5, "vote_count_gte": 200,
    },
    {
        "slug": "long_films_worth_it",
        "title": "Five films over three hours that earn every minute",
        "subtitle": "no bathroom breaks.",
        "category": "FILM LIST",
        "caption": "Five films where the runtime is the point. You need all of it. Sources via TMDB.",
        "closing_headline": "Block out the day.",
        "runtime_gte": 180, "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "first_films",
        "title": "Five extraordinary debut films",
        "subtitle": "the ones that arrived fully formed.",
        "category": "FILM LIST",
        "caption": "Five filmmakers who got it completely right on the first attempt. Sources via TMDB.",
        "closing_headline": "No second album problem here.",
        "vote_avg_gte": 7.5, "vote_count_gte": 1000,
        "genre_ids": [18, 53, 80],
    },
    {
        "slug": "road_movies",
        "title": "Five road movies that go somewhere real",
        "subtitle": "the destination is not the point.",
        "category": "FILM LIST",
        "caption": "Five road movies that use the journey to say something about how we live. Sources via TMDB.",
        "closing_headline": "Keep moving.",
        "genre_ids": [12, 18], "vote_avg_gte": 7.2,
    },

    # ------------------------------------------------------------------ #
    # Topic-based                                                          #
    # ------------------------------------------------------------------ #
    {
        "slug": "films_about_ai",
        "title": "Five films about artificial intelligence that got it right",
        "subtitle": "fiction that became non-fiction.",
        "category": "SCI-FI LIST",
        "caption": "Five films about AI that anticipated where we are now. Watch them differently this time. Sources via TMDB.",
        "closing_headline": "They tried to tell us.",
        "genre_ids": [878], "vote_avg_gte": 7.0,
    },
    {
        "slug": "heist_films",
        "title": "Five heist films where the plan actually matters",
        "subtitle": "the caper is the cinema.",
        "category": "CRIME LIST",
        "caption": "Five heist films where the mechanics of the job are what make it work. Sources via TMDB.",
        "closing_headline": "Everyone loves a good plan.",
        "genre_ids": [80, 53], "vote_avg_gte": 7.2, "vote_count_gte": 2000,
    },
    {
        "slug": "space_films",
        "title": "Five space films that take the science seriously",
        "subtitle": "not everything blows up.",
        "category": "SCI-FI LIST",
        "caption": "Five space films that understand what is actually out there is stranger than the fiction. Sources via TMDB.",
        "closing_headline": "Space is the point.",
        "genre_ids": [878, 12], "vote_avg_gte": 7.0, "vote_count_gte": 1000,
    },
    {
        "slug": "prison_films",
        "title": "Five prison films that are about much more than prison",
        "subtitle": "confinement as metaphor.",
        "category": "DRAMA LIST",
        "caption": "Five prison films that use captivity to say something about freedom. Sources via TMDB.",
        "closing_headline": "The walls are always symbolic.",
        "genre_ids": [18, 80], "vote_avg_gte": 7.3,
    },
    {
        "slug": "sports_films",
        "title": "Five sports films for people who do not like sports",
        "subtitle": "they are not really about sport.",
        "category": "DRAMA LIST",
        "caption": "Five sports films that use the game to talk about something much bigger. Sources via TMDB.",
        "closing_headline": "You do not have to care about sport.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "political_films",
        "title": "Five political films that do not take sides",
        "subtitle": "they just show you.",
        "category": "DRAMA LIST",
        "caption": "Five political films that describe how power actually works, without telling you what to think. Sources via TMDB.",
        "closing_headline": "An informed audience is a dangerous audience.",
        "genre_ids": [36, 18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "addiction_films",
        "title": "Five films about addiction that do not glamorise it",
        "subtitle": "unflinching.",
        "category": "DRAMA LIST",
        "caption": "Five films about addiction that are honest about what it actually looks like. Sources via TMDB.",
        "closing_headline": "No glamour. Just truth.",
        "genre_ids": [18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "memory_identity_films",
        "title": "Five films about memory and identity",
        "subtitle": "you are not who you think you are.",
        "category": "FILM LIST",
        "caption": "Five films that interrogate how we construct who we are from what we remember. Sources via TMDB.",
        "closing_headline": "Memory is unreliable. Cinema is proof.",
        "genre_ids": [53, 18, 878], "vote_avg_gte": 7.3,
    },
    {
        "slug": "war_antiwar",
        "title": "Five war films that argue against war",
        "subtitle": "they use the genre against itself.",
        "category": "WAR LIST",
        "caption": "Five war films that make the strongest possible case against it. Sources via TMDB.",
        "closing_headline": "The genre as protest.",
        "genre_ids": [10752, 18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "survival_films",
        "title": "Five survival films where the human element is the point",
        "subtitle": "not action. endurance.",
        "category": "FILM LIST",
        "caption": "Five survival films where the question is not whether they survive - it is who they become. Sources via TMDB.",
        "closing_headline": "Survival is a choice.",
        "genre_ids": [12, 18, 53], "vote_avg_gte": 7.2, "vote_count_gte": 1000,
    },
    {
        "slug": "journalism_films",
        "title": "Five films about journalism at its best",
        "subtitle": "when it worked.",
        "category": "DRAMA LIST",
        "caption": "Five films about journalism that remind you why it matters. Sources via TMDB.",
        "closing_headline": "The press is the point.",
        "genre_ids": [18, 36], "vote_avg_gte": 7.2,
    },
    {
        "slug": "family_drama",
        "title": "Five films about family that do not have easy answers",
        "subtitle": "complicated people, complicated love.",
        "category": "DRAMA LIST",
        "caption": "Five films about family that resist resolution. Sources via TMDB.",
        "closing_headline": "Families are not tidy.",
        "genre_ids": [18], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },
    {
        "slug": "coming_of_age",
        "title": "Five coming-of-age films that get it exactly right",
        "subtitle": "the ones that make you feel it again.",
        "category": "DRAMA LIST",
        "caption": "Five coming-of-age films that capture something true about becoming a person. Sources via TMDB.",
        "closing_headline": "Everyone is still becoming.",
        "genre_ids": [18, 35], "vote_avg_gte": 7.3, "vote_count_gte": 1000,
    },

    # ------------------------------------------------------------------ #
    # Director spotlights (with TMDB person IDs)                          #
    # ------------------------------------------------------------------ #
    {
        "slug": "kubrick_retrospective",
        "title": "Five Stanley Kubrick films ranked by how much they disturb you",
        "subtitle": "from unsettling to unwatchable. lovingly.",
        "category": "DIRECTOR LIST",
        "caption": "Five Stanley Kubrick films. Each one a controlled act of provocation. Sources via TMDB.",
        "closing_headline": "There will never be another Kubrick.",
        "with_people": "240", "vote_avg_gte": 7.5,
    },
    {
        "slug": "scorsese_retrospective",
        "title": "Five Scorsese films that are not Goodfellas",
        "subtitle": "there is a whole filmography out there.",
        "category": "DIRECTOR LIST",
        "caption": "Five Martin Scorsese films that get overshadowed by the obvious ones. Sources via TMDB.",
        "closing_headline": "He made more than you think.",
        "with_people": "1032", "vote_avg_gte": 7.2,
    },
    {
        "slug": "coen_brothers",
        "title": "Five Coen Brothers films to watch in order of darkness",
        "subtitle": "they find it funny. so will you.",
        "category": "DIRECTOR LIST",
        "caption": "Five films from the Coen Brothers. Bleaker, funnier, smarter than everyone else. Sources via TMDB.",
        "closing_headline": "Nobody does it like them.",
        "with_people": "1223,1224", "vote_avg_gte": 7.2,
    },
    {
        "slug": "wong_kar_wai",
        "title": "Five Wong Kar-wai films about longing",
        "subtitle": "every frame is about missing someone.",
        "category": "DIRECTOR LIST",
        "caption": "Five films from Wong Kar-wai. No one films longing the way he does. Sources via TMDB.",
        "closing_headline": "Memory and desire, on film.",
        "with_people": "12453", "vote_avg_gte": 7.3,
    },
    {
        "slug": "lynch_films",
        "title": "Five David Lynch films from least to most inexplicable",
        "subtitle": "start here, then surrender.",
        "category": "DIRECTOR LIST",
        "caption": "Five David Lynch films. He is not trying to confuse you. He is trying to show you something real. Sources via TMDB.",
        "closing_headline": "Logic is overrated.",
        "with_people": "5765", "vote_avg_gte": 7.0,
    },
    {
        "slug": "kurosawa_films",
        "title": "Five Kurosawa films that shaped every action film after them",
        "subtitle": "you have already seen these. you just do not know it.",
        "category": "DIRECTOR LIST",
        "caption": "Five Akira Kurosawa films. The blueprint for most of the action cinema you love. Sources via TMDB.",
        "closing_headline": "The original. All others are cover versions.",
        "with_people": "7175", "vote_avg_gte": 7.5,
    },
    {
        "slug": "tarkovsky_films",
        "title": "Five Tarkovsky films for when you have patience",
        "subtitle": "slow cinema. permanent effect.",
        "category": "DIRECTOR LIST",
        "caption": "Five Andrei Tarkovsky films. Deliberately slow. Permanently affecting. Sources via TMDB.",
        "closing_headline": "Take your time. He did.",
        "with_people": "12432", "vote_avg_gte": 7.5,
    },
    {
        "slug": "fassbinder_films",
        "title": "Five Fassbinder films that made New German Cinema",
        "subtitle": "furious, prolific, essential.",
        "category": "DIRECTOR LIST",
        "caption": "Five Rainer Werner Fassbinder films. He made 40 in 13 years. These are the ones to start with. Sources via TMDB.",
        "closing_headline": "A filmmaker who burned too bright.",
        "with_people": "7232", "vote_avg_gte": 7.2,
    },

    # ------------------------------------------------------------------ #
    # Award + critical recognition                                         #
    # ------------------------------------------------------------------ #
    {
        "slug": "palme_dor_winners",
        "title": "Five Palme d'Or winners worth the hype",
        "subtitle": "cannes got these right.",
        "category": "FILM LIST",
        "caption": "Five winners of the Palme d'Or at Cannes that genuinely deserved it. Sources via TMDB.",
        "closing_headline": "The jury was correct.",
        "vote_avg_gte": 7.5, "vote_count_gte": 2000,
        "genre_ids": [18, 53, 80],
    },
    {
        "slug": "overlooked_oscar_winners",
        "title": "Five Best Picture winners nobody talks about anymore",
        "subtitle": "the academy moves on. these deserve better.",
        "category": "FILM LIST",
        "caption": "Five Best Picture winners that have been eclipsed by other films from their year. They should not be forgotten. Sources via TMDB.",
        "closing_headline": "The academy was right. Once.",
        "vote_avg_gte": 7.0, "vote_count_gte": 3000,
        "genre_ids": [18, 36],
    },
    {
        "slug": "cult_classics",
        "title": "Five cult films that have earned the label",
        "subtitle": "not cult because they are bad. cult because they are right.",
        "category": "FILM LIST",
        "caption": "Five films with cult followings that exist for good reason. Sources via TMDB.",
        "closing_headline": "Some films take time to find their audience.",
        "vote_avg_gte": 7.0, "vote_count_gte": 1000,
        "genre_ids": [53, 878, 27],
    },
    {
        "slug": "films_critics_hated",
        "title": "Five films critics hated that audiences were right about",
        "subtitle": "the audience wins sometimes.",
        "category": "FILM LIST",
        "caption": "Five films that critics dismissed and time proved them wrong. Sources via TMDB.",
        "closing_headline": "The crowd is not always wrong.",
        "vote_avg_gte": 7.0, "vote_count_gte": 5000,
    },

    # ------------------------------------------------------------------ #
    # More genre combos                                                    #
    # ------------------------------------------------------------------ #
    {
        "slug": "neo_noir",
        "title": "Five neo-noir films for when you want shadows",
        "subtitle": "everybody lies. nobody wins.",
        "category": "CRIME LIST",
        "caption": "Five neo-noir films that inherit everything the genre promised and deliver it with modern dread. Sources via TMDB.",
        "closing_headline": "The darkness is comfortable here.",
        "genre_ids": [80, 53], "year_gte": 1990, "vote_avg_gte": 7.2,
    },
    {
        "slug": "psychological_horror",
        "title": "Five psychological horror films that never show the monster",
        "subtitle": "the scariest thing is your own mind.",
        "category": "HORROR LIST",
        "caption": "Five horror films where the horror is interior. No jump scares. Pure dread. Sources via TMDB.",
        "closing_headline": "You will question yourself after.",
        "genre_ids": [27, 53], "vote_avg_gte": 7.0,
    },
    {
        "slug": "arthouse_accessible",
        "title": "Five arthouse films that are actually accessible",
        "subtitle": "slow cinema does not have to be difficult.",
        "category": "FILM LIST",
        "caption": "Five arthouse films that reward patience without demanding a film degree. Sources via TMDB.",
        "closing_headline": "Slow is not the same as obscure.",
        "vote_avg_gte": 7.5, "vote_count_gte": 500,
        "genre_ids": [18],
    },
    {
        "slug": "crime_masterpieces",
        "title": "Five crime films that are also great literature",
        "subtitle": "the genre at its most serious.",
        "category": "CRIME LIST",
        "caption": "Five crime films that use the genre to do the work of great novels. Sources via TMDB.",
        "closing_headline": "Crime fiction is serious fiction.",
        "genre_ids": [80], "vote_avg_gte": 7.5, "vote_count_gte": 2000,
    },
    {
        "slug": "black_comedy_essential",
        "title": "Five black comedies that only get darker on rewatch",
        "subtitle": "funnier every time.",
        "category": "COMEDY LIST",
        "caption": "Five black comedies that reveal new layers of bleakness on every viewing. Sources via TMDB.",
        "closing_headline": "It gets funnier as you get older. Worryingly.",
        "genre_ids": [35, 53], "vote_avg_gte": 7.3,
    },
    {
        "slug": "female_directors",
        "title": "Five films directed by women that changed cinema",
        "subtitle": "not a list. a correction.",
        "category": "FILM LIST",
        "caption": "Five films directed by women that belong in any serious conversation about the art form. Sources via TMDB.",
        "closing_headline": "Half of cinema was missing. These found it.",
        "vote_avg_gte": 7.2, "vote_count_gte": 500,
        "genre_ids": [18, 53],
    },
    {
        "slug": "music_films",
        "title": "Five music films that capture something real",
        "subtitle": "not biopics. the actual thing.",
        "category": "MUSIC LIST",
        "caption": "Five films about music that capture what it feels like from the inside. Sources via TMDB.",
        "closing_headline": "Some things only music can say.",
        "genre_ids": [10402, 18], "vote_avg_gte": 7.2,
    },
    {
        "slug": "environmental_films",
        "title": "Five films about the natural world that will change you",
        "subtitle": "after these, the news makes sense.",
        "category": "DOCUMENTARY LIST",
        "caption": "Five films about what we are doing to the planet. Uncomfortable but essential. Sources via TMDB.",
        "closing_headline": "Watch now. Act later.",
        "genre_ids": [99], "vote_avg_gte": 7.2,
    },
    {
        "slug": "anthology_films",
        "title": "Five anthology films where every segment is worth it",
        "subtitle": "short films deserve more credit.",
        "category": "FILM LIST",
        "caption": "Five anthology films where the format serves the story rather than fragmenting it. Sources via TMDB.",
        "closing_headline": "The short form is underrated.",
        "genre_ids": [18, 35, 27], "vote_avg_gte": 7.2,
    },

]
